FROM node:16-alpine3.14 As builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install 
COPY dx.material.broadridge.css ./node_modules/devextreme/dist/css

# Copy local nuxt code to the container
COPY . .

# Build production app

RUN npm run build && npm prune

FROM nginx:1.20.2-alpine

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80