# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.0-dev
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-02-16T05:54:50Z"
  labels:
    app: gloss-api-client
  name: gloss-api-client
spec:
  containers:
  - command:
    - /docker-entrypoint.sh
    - nginx
    - -g
    - daemon off;
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NGINX_VERSION
      value: 1.19.0
    - name: NJS_VERSION
      value: 0.4.1
    - name: PKG_RELEASE
      value: "1"
    image: localhost/gloss-api-client:01
    name: gloss-api-client
    ports:
    - containerPort: 80
      hostPort: 4333
      protocol: TCP
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    workingDir: /
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-02-16T05:54:50Z"
  labels:
    app: gloss-api-client
  name: gloss-api-client
spec:
  ports:
  - name: "80"
    nodePort: 31361
    port: 80
    protocol: TCP
    targetPort: 0
  selector:
    app: gloss-api-client
  type: NodePort
status:
  loadBalancer: {}
