apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: backend-ingress
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: gloss-api-backend
            servicePort: 3010
          path: /backend(/|$)(.*)

--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: client-ingress
spec:
  rules:
  - http:
      paths:
        - backend:
           serviceName: gloss-api-client
           servicePort: 80
          path: /

