apiVersion: v1
kind: ConfigMap
metadata:
  name: gloss-api-backend-config
  labels:
    app: gloss-api-config
data:
  POSTGRESQL_URL: postgresql://admin:admin123@postgres:5432/postgresdb?schema=public&sslmode=prefer
  POSTGRESQL_USER: admin
  POSTGRESQL_PASSWORD: admin123
  POSTGRES_DB: postgresdb
  PYTHON_RETURN_MSG: 'True'
  PYTHON_POST_MSG: 'False'
  PYTHON_HOST: http://localhost:5000
  CORS_ENABLE: "1"
  PORT: "3010"
  APPLICATION: Gloss Backend API
  GRAPHQL_SCHEMA_DEST: /src/schema.graphql
  GRAPHQL_DEBUG: "1"
  PLAYGROUND_ENABLE: "1"
  SWAGGER_ENABLE: "1"
  SWAGGER_TITLE: Nestjs FTW
  SWAGGER_DESCRIPTION: gloss api backend server
  SWAGGER_VERSION: "1.5"
  SWAGGER_PATH: api
  JWT_SECRET: m&XAFzBpM3es
  JWT_EXPIRES_IN: 2m
  JWT_REFRESH_IN: 7d
  BCRYPT_SALT_OR_ROUNDS: "10"